---
title: "palmerpenguins"
output: html_document
date: "2024-01-12"
---

# These were examples (good and bad!) for the GHGA Beginner's Guide to data vis webinar in January 2024
```{r setup, include=FALSE}
install.packages("palmerpenguins")
library(palmerpenguins)
library(ggplot2)
library(ggbreak)
data(package = 'palmerpenguins')
```

```{r}
library(palmerpenguins)
library(ggplot2)
```

```{r}
head(penguins)
#examples on axes

flipper_bill <- ggplot(data = penguins,
                         aes(x = flipper_length_mm,
                             y = bill_length_mm)) +
  geom_point(aes(color = species, 
                 shape = species),
             size = 3,
             alpha = 0.8) +
  scale_color_manual(values = c("darkorange","purple","cyan4")) +
  labs(title = "Flipper and bill length",
       subtitle = "Dimensions for Adelie, Chinstrap and Gentoo Penguins at Palmer Station LTER",
       x = "Flipper length (mm)",
       y = "Bill length (mm)",
       color = "Penguin species",
       shape = "Penguin species") +
  theme_bw() + 
  theme(legend.position = c(0.85, 0.20),
        plot.title.position = "plot",
        plot.caption = element_text(hjust = 0, face= "italic"),
        plot.caption.position = "plot")

flipper_bill
```

```{r}
ggplot(data = penguins, aes(x = flipper_length_mm, y = bill_length_mm)) +
  geom_point(aes(color = species, shape = species),size = 3, alpha = 0.8) +
  scale_color_manual(values = c("darkorange","purple","cyan4")) +
  labs(title = "Flipper and bill length",
       subtitle = "Dimensions for Adelie, Chinstrap and Gentoo Penguins at Palmer Station LTER",
       x = "Flipper length (mm)",
       y = "Bill length (mm)",
       color = "Penguin species",
       shape = "Penguin species")

```

```{r}
head(penguins)
#examples on axes

flipper_bill_red <- ggplot(data = penguins,
                         aes(x = flipper_length_mm,
                             y = bill_length_mm)) +
  geom_point(aes(color = species, 
                 shape = species),
             size = 3,
             alpha = 0.8) +
  scale_color_manual(values = c("grey70","grey70","red")) +
  labs(title = "Flipper and bill length",
       subtitle = "Dimensions for Adelie, Chinstrap and Gentoo Penguins at Palmer Station LTER",
       x = "Flipper length (mm)",
       y = "Bill length (mm)",
       color = "Penguin species",
       shape = "Penguin species") +
  theme_bw() + 
  theme(legend.position = c(0.85, 0.20),
        plot.title.position = "plot",
        plot.caption = element_text(hjust = 0, face= "italic"),
        plot.caption.position = "plot")

flipper_bill_red


flipper_bill_rainbow <- ggplot(data = penguins,
                         aes(x = flipper_length_mm,
                             y = bill_length_mm)) +
  geom_point(aes(color = species, 
                 shape = species),
             size = 3,
             alpha = 0.8) +
  scale_color_manual(values = c("grey70","grey70","red")) +
  labs(title = "Flipper and bill length",
       subtitle = "Dimensions for Adelie, Chinstrap and Gentoo Penguins at Palmer Station LTER",
       x = "Flipper length (mm)",
       y = "Bill length (mm)",
       color = "Penguin species",
       shape = "Penguin species") +
  theme_bw() + 
  theme(legend.position = c(0.85, 0.20),
        plot.title.position = "plot",
        plot.caption = element_text(hjust = 0, face= "italic"),
        plot.caption.position = "plot")

flipper_bill_red
```

```{r}

head(penguins)
#examples on axes

flipper_bill <- ggplot(data = penguins,
                         aes(x = bill_depth_mm,
                             y = bill_length_mm)) +
  geom_point(aes(color = species, 
                 shape = species),
             size = 3,
             alpha = 0.8) +
  scale_color_manual(values = c("darkorange","purple","cyan4")) +
  labs(title = "Flipper and bill length",
       subtitle = "Dimensions for Adelie, Chinstrap and Gentoo Penguins at Palmer Station LTER",
       x = "Flipper length (mm)",
       y = "Bill length (mm)",
       color = "Penguin species",
       shape = "Penguin species") +
  theme_bw() + 
  theme(legend.position = c(0.85, 0.20),
        plot.title.position = "plot",
        plot.caption = element_text(hjust = 0, face= "italic"),
        plot.caption.position = "plot")

flipper_bill
```

```{r}
p1 <- ggplot(penguins, aes(x=species, fill=species)) +
  geom_bar(stat = "count") +
  scale_fill_manual(values = c("darkorange","purple","cyan4")) +
  scale_y_continuous("# of penguins observed") +
  theme_bw() +
  theme(plot.title.position = "plot",
        plot.caption = element_text(hjust = 0, face= "italic"),
        plot.caption.position = "plot")

p2 <- ggplot(penguins, aes(x=species, fill=species)) +
  geom_bar(stat = "count") +
  scale_y_break(c(70, 110), scales = "free") +
  scale_fill_manual(values = c("darkorange","purple","cyan4")) +
  scale_y_continuous("# of penguins observed") +
  theme_bw() +
  theme(plot.title.position = "plot",
        plot.caption = element_text(hjust = 0, face= "italic"),
        plot.caption.position = "plot")

p3 <- ggplot(penguins, aes(x=species, fill=species)) +
  geom_bar(stat = "count") +
  coord_cartesian(ylim = c(50, 153)) +
  scale_fill_manual(values = c("darkorange","purple","cyan4")) +
  scale_y_continuous("# of penguins observed") +
  theme_bw() +
  theme(plot.title.position = "plot",
        plot.caption = element_text(hjust = 0, face= "italic"),
        plot.caption.position = "plot")

p1 + p2 + p3


p1

p2

p3

ggplot(penguins, aes(x=island)) +
  geom_bar(stat = "count") +
  scale_y_break(c(55, 85))

ggplot(penguins, aes(x=year)) +
  geom_bar(stat = "count")
```

```{r}
# scaling

flipper_bill_1 <- ggplot(data = penguins,
                         aes(x = flipper_length_mm,
                             y = body_mass_g)) +
  geom_point(aes(color = species, 
                 shape = species),
             size = 3,
             alpha = 0.8) +
  scale_color_manual(values = c("darkorange","purple","cyan4")) +
  labs(title = "Flipper length and body mass",
       subtitle = "Dimensions for Adelie, Chinstrap and Gentoo Penguins at Palmer Station LTER",
       x = "Flipper length (mm)",
       y = "Body mass (g)",
       color = "Penguin species",
       shape = "Penguin species") +
  theme_bw() + 
  theme(legend.position = c(0.80, 0.18),
        plot.title.position = "plot",
        plot.caption = element_text(hjust = 0, face= "italic"),
        plot.caption.position = "plot", 
        aspect.ratio = 1)

flipper_bill_1


flipper_bill_2 <- ggplot(data = penguins,
                         aes(x = flipper_length_mm,
                             y = body_mass_g)) +
  geom_point(aes(color = species, 
                 shape = species),
             size = 3,
             alpha = 0.8) +
  scale_color_manual(values = c("darkorange","purple","cyan4")) +
  labs(title = "Flipper length and body mass",
       subtitle = "Dimensions for Adelie, Chinstrap and Gentoo Penguins at Palmer Station LTER",
       x = "Flipper length (mm)",
       y = "Body mass (g)",
       color = "Penguin species",
       shape = "Penguin species") +
  theme_bw() + 
  theme(legend.position = c(0.85, 0.20),
        plot.title.position = "plot",
        plot.caption = element_text(hjust = 0, face= "italic"),
        plot.caption.position = "plot")

flipper_bill_2

flipper_bill_3 <- ggplot(data = penguins,
                         aes(x = flipper_length_mm,
                             y = body_mass_g)) +
  geom_point(aes(color = species, 
                 shape = species),
             size = 3,
             alpha = 0.8) +
  scale_color_manual(values = c("darkorange","purple","cyan4")) +
  coord_cartesian(xlim=c(0,6000)) +
  labs(title = "Flipper length and body mass",
       subtitle = "Dimensions for Adelie, Chinstrap and Gentoo Penguins at Palmer Station LTER",
       x = "Flipper length (mm)",
       y = "Body mass (g)",
       color = "Penguin species",
       shape = "Penguin species") +
  theme_bw() + 
  theme(legend.position = c(0.75, 0.20),
        plot.title.position = "plot",
        plot.caption = element_text(hjust = 0, face= "italic"),
        plot.caption.position = "plot", 
        aspect.ratio = 1)

flipper_bill_3
```

```{r}
library(xkcd)
g + theme_xkcd()
```


