---
title: "ggplot"
output: html_document
date: "2024-02-15"
---

```{r setup, include=FALSE}
library(palmerpenguins)
library(ggplot2)
data(package = 'palmerpenguins')
```


```{r}
head(penguins)

```

```{r, include=FALSE, echo=FALSE, warning=FALSE}
# ggplot template
# below is pseudocode! fill in info in <> to execute
ggplot(data = <default data set>,
       aes(x = <default x axis variable>,
           y = <default y axis variable>,
           ... <other default aesthetic mappings>),
       ... <other plot defaults>) +
  
  geom_<geom_type>(aes(size = <size variable for this geom>,
                   ... <other aesthetic mappings>),
                   data = <data for this specific geom>,
                   stat = <statistic string or function>,
                   position = <position string or function>,
                   color = <"fixed color specification">,
                   ... < other arguments, possibly passed to the _stat_ function) +
  
  scale_<aesthetic>_type(name = <"scale label>",
                         breaks = <where to put the tick marks>,
                         labels = <labels for tick marks>,
                         ... <other options for the scale>) +
  
  theme(plot.background = element_rect(fill = "gray"),
        ... <other theme elements>)

```

```{r}
ggplot(data = penguins,aes(x = flipper_length_mm, y = bill_length_mm)) +
  geom_point(aes(color = species, 
                 shape = species),
             size = 3,
             alpha = 0.8) +
  scale_color_manual(values = c("darkorange","purple","cyan4")) +
  labs(title = "Flipper and bill length",
       subtitle = "Dimensions for Adelie, Chinstrap and Gentoo Penguins at Palmer Station LTER",
       x = "Flipper length (mm)",
       y = "Bill length (mm)",
       color = "Penguin species",
       shape = "Penguin species") +
  theme_bw() + 
  theme(legend.position = c(0.85, 0.20),
        plot.title.position = "plot",
        plot.caption = element_text(hjust = 0, face= "italic"),
        plot.caption.position = "plot")
```


```{r}
# grammar of graphics example

penguin_colors = c("darkorange","purple","cyan4")

ggplot(penguins, aes(x=species, fill=species)) +
  geom_bar(stat = "count") +
  scale_fill_manual(values=penguin_colors, name="Species") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r}
# themes
g = ggplot(penguins, aes(x=species, y = bill_length_mm, fill=species)) +
  geom_violin(col = NA) +
  scale_fill_manual(values=penguin_colors, name="Species")

g

```

```{r}
g + theme_dark()
```

```{r}
g + theme_minimal()
```

```{r}
library(ggthemes)
g + theme_economist_white()
```
```{r}
# cowplot theme
library(cowplot)

g + theme_cowplot()
```
```{r}
# cowplot compound plots

p1 <- ggplot(penguins, aes(x=species, y = bill_length_mm, fill=species)) +
  geom_violin(col = NA) +
  scale_fill_manual(values=penguin_colors, name="Species")

p2 <- ggplot(penguins, aes(x=species, y = bill_length_mm, fill=species)) +
  geom_violin(col = NA) +
  scale_fill_manual(values=penguin_colors, name="Species") +
  theme_cowplot()

plot_grid(p1, p2, labels = c('A', 'B'), rel_widths = c(1, 1))

```

```{r}
# use different aesthetic

ggplot(data = penguins,aes(x = flipper_length_mm, 
                           y = bill_length_mm)) +
  geom_point(aes(color = species, 
                 shape = island,
                 size = body_mass_g,
                 alpha = 0.8)) +
  scale_color_manual(values = c("darkorange","purple","cyan4")) +
  scale_alpha(guide = 'none') +
  labs(title = "Flipper and bill length",
       subtitle = "Dimensions for Adelie, Chinstrap and Gentoo Penguins at Palmer Station LTER",
       x = "Flipper length (mm)",
       y = "Bill length (mm)",
       color = "Penguin species",
       shape = "Island",
       size = "Body mass (g)") +
  theme_bw()
```
```{r}
ggplot(data = penguins,aes(x = flipper_length_mm, 
                           y = bill_length_mm)) +
  geom_point(aes(color = species, 
                 shape = species,
                 alpha = 0.8)) +
  facet_wrap(~island) +
  scale_color_manual(values = c("darkorange","purple","cyan4")) +
  scale_alpha(guide = 'none') +
  labs(title = "Flipper and bill length",
       subtitle = "Dimensions for Adelie, Chinstrap and Gentoo Penguins at Palmer Station LTER",
       x = "Flipper length (mm)",
       y = "Bill length (mm)",
       color = "Penguin species",
       shape = "Penguin species") +
  theme_bw()
  
```

```{r}
ggplot(data = penguins,aes(x = flipper_length_mm, 
                           y = bill_length_mm)) +
  geom_point(aes(color = species, 
                 shape = species,
                 alpha = 0.8)) +
  facet_wrap(~island, ncol=2) +
  scale_color_manual(values = c("darkorange","purple","cyan4")) +
  scale_alpha(guide = 'none') +
  labs(title = "Flipper and bill length",
       subtitle = "Dimensions for Adelie, Chinstrap and Gentoo Penguins at Palmer Station LTER",
       x = "Flipper length (mm)",
       y = "Bill length (mm)",
       color = "Penguin species",
       shape = "Penguin species") +
  theme_bw()
  
```



```{r}
ggplot(data = penguins,aes(x = flipper_length_mm, 
                           y = bill_length_mm)) +
  geom_point(aes(color = species, 
                 shape = species,
                 alpha = 0.8)) +
  facet_grid(island ~ year) +
  scale_color_manual(values = c("darkorange","purple","cyan4")) +
  scale_alpha(guide = 'none') +
  labs(title = "Flipper and bill length",
       subtitle = "Dimensions for Adelie, Chinstrap and Gentoo Penguins at Palmer Station LTER",
       x = "Flipper length (mm)",
       y = "Bill length (mm)",
       color = "Penguin species",
       shape = "Penguin species") +
  theme_bw()
  
```
```{r}
# ChatGPT example
library(ggplot2)
library(palmerpenguins)
library(viridis)

# Load Palmer Penguin dataset
data("penguins")

# Create plot with viridis color palette
ggplot(data = penguins, aes(x = flipper_length_mm, y = bill_length_mm)) +
  geom_point(aes(color = species, shape = species), alpha = 0.8) +
  scale_color_viridis(discrete = TRUE) +  # Using viridis color palette
  scale_alpha(guide = 'none') +
  labs(title = "Flipper and Bill Length",
       subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins at Palmer Station LTER",
       x = "Flipper Length (mm)",
       y = "Bill Length (mm)",
       color = "Penguin Species",
       shape = "Penguin Species") +
  theme_bw()
```

